import type {
  BusinessSettings,
  Client,
  EquipmentDeal,
  Lead,
  Task,
} from "./types"

export const COURSE_CATALOG: BusinessSettings["courses"] = [
  {
    type: "עזרה ראשונה 22 שעות",
    hours: 22,
    syllabusUrl: "https://example.com/syllabus/first-aid-22",
    presentationUrl: "https://example.com/ppt/first-aid-22",
    bookletUrl: "https://example.com/booklet/first-aid-22.pdf",
  },
  {
    type: "עזרה ראשונה 44 שעות",
    hours: 44,
    syllabusUrl: "https://example.com/syllabus/first-aid-44",
    presentationUrl: "https://example.com/ppt/first-aid-44",
    bookletUrl: "https://example.com/booklet/first-aid-44.pdf",
  },
  {
    type: "בטיחות אש",
    hours: 8,
    syllabusUrl: "https://example.com/syllabus/fire-safety",
    presentationUrl: "https://example.com/ppt/fire-safety",
    bookletUrl: "https://example.com/booklet/fire-safety.pdf",
  },
  {
    type: "החייאה CPR",
    hours: 6,
    syllabusUrl: "https://example.com/syllabus/cpr",
    presentationUrl: "https://example.com/ppt/cpr",
    bookletUrl: "https://example.com/booklet/cpr.pdf",
  },
  {
    type: "בטיחות בגובה",
    hours: 12,
    syllabusUrl: "https://example.com/syllabus/height-safety",
    presentationUrl: "https://example.com/ppt/height-safety",
    bookletUrl: "https://example.com/booklet/height-safety.pdf",
  },
]

export const CATEGORIES = [
  "גני ילדים",
  "בתי ספר",
  "מפעלים",
  "משרדים",
  "מסעדות",
  "עמותות",
  "אחר",
]

export const INSTRUCTORS = ["דנה כהן", "אבי לוי", "מירב שרון", "יוסי מזרחי"]

export const DEFAULT_SETTINGS: BusinessSettings = {
  businessName: "מדריכים בע\"מ",
  tiktokUrl: "https://tiktok.com/@madrichim",
  facebookUrl: "https://facebook.com/madrichim",
  instagramUrl: "https://instagram.com/madrichim",
  courses: COURSE_CATALOG,
}

function daysFromNow(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() + days)
  return d.toISOString().slice(0, 10)
}

export const DEMO_CLIENTS: Client[] = [
  {
    id: "c1",
    name: "גן שמש",
    phone: "0521234567",
    city: "תל אביב",
    contacts: [
      { id: "ct1", name: "רונית ברק", role: "מנהלת", phone: "0521234567", email: "ronit@gan-shemesh.co.il" },
      { id: "ct2", name: "שירן דוד", role: "מזכירה", phone: "0521234568" },
    ],
    createdAt: daysFromNow(-120),
  },
  {
    id: "c2",
    name: "מפעלי הגליל",
    phone: "0539876543",
    city: "כרמיאל",
    contacts: [
      { id: "ct3", name: "משה פרץ", role: "מנהל בטיחות", phone: "0539876543", email: "moshe@galil.co.il" },
    ],
    createdAt: daysFromNow(-60),
  },
  {
    id: "c3",
    name: "בית ספר רמון",
    phone: "0547778899",
    city: "באר שבע",
    contacts: [{ id: "ct4", name: "טלי אבנר", role: "סגנית מנהל", phone: "0547778899" }],
    createdAt: daysFromNow(-30),
  },
  {
    id: "c4",
    name: "מסעדת הים",
    phone: "0501112233",
    city: "חיפה",
    contacts: [{ id: "ct5", name: "עומר גל", role: "בעלים", phone: "0501112233" }],
    createdAt: daysFromNow(-10),
  },
]

export const DEMO_LEADS: Lead[] = [
  {
    id: "l1",
    clientId: "c4",
    name: "מסעדת הים",
    phone: "0501112233",
    email: "omer@hayam.co.il",
    urgent: true,
    status: "new",
    customerType: "new",
    courseType: "החייאה CPR",
    courseHours: 6,
    category: "מסעדות",
    pricingType: "per_participant",
    pricePerUnit: 180,
    participantsCount: 12,
    totalPrice: 2160,
    certificateDelivery: "digital",
    address: { street: "שדרות הים", houseNumber: "44", city: "חיפה" },
    contactName: "עומר גל",
    notes: "מעוניינים בהדרכה לצוות המטבח בהקדם",
    participants: [],
    expenses: [],
    createdAt: daysFromNow(-2),
    updatedAt: daysFromNow(-1),
  },
  {
    id: "l2",
    clientId: "c3",
    name: "בית ספר רמון",
    phone: "0547778899",
    urgent: false,
    status: "closed",
    customerType: "new",
    courseType: "עזרה ראשונה 22 שעות",
    courseHours: 22,
    category: "בתי ספר",
    pricingType: "global",
    pricePerUnit: 0,
    participantsCount: 20,
    totalPrice: 4500,
    certificateDelivery: "mail",
    address: { street: "רחוב האלון", houseNumber: "12", city: "באר שבע", zip: "8410501" },
    date: daysFromNow(5),
    time: "09:00",
    instructor: "דנה כהן",
    contactName: "טלי אבנר",
    notes: "לוודא חניה למדריך",
    quoteSentAt: daysFromNow(-8),
    participants: [],
    expenses: [{ id: "e1", type: "נסיעות", amount: 120, hasReceipt: true, date: daysFromNow(-1) }],
    createdAt: daysFromNow(-15),
    updatedAt: daysFromNow(-3),
  },
  {
    id: "l3",
    clientId: "c2",
    name: "מפעלי הגליל",
    phone: "0539876543",
    email: "moshe@galil.co.il",
    urgent: false,
    status: "pending_certificates",
    customerType: "existing",
    courseType: "בטיחות אש",
    courseHours: 8,
    category: "מפעלים",
    pricingType: "per_participant",
    pricePerUnit: 150,
    participantsCount: 15,
    totalPrice: 2250,
    certificateDelivery: "physical",
    address: { street: "האורגים", houseNumber: "3", city: "כרמיאל" },
    date: daysFromNow(-3),
    time: "14:00",
    instructor: "אבי לוי",
    contactName: "משה פרץ",
    trainingIndex: 3,
    participants: [
      { id: "p1", name: "דוד ישראלי", idNumber: "301234567" },
      { id: "p2", name: "שרה כהן", idNumber: "302345678" },
      { id: "p3", name: "יעקב לוי", idNumber: "303456789" },
    ],
    expenses: [{ id: "e2", type: "ציוד מתכלה", amount: 300, hasReceipt: true, date: daysFromNow(-3) }],
    createdAt: daysFromNow(-40),
    updatedAt: daysFromNow(-3),
  },
  {
    id: "l4",
    clientId: "c1",
    name: "גן שמש",
    phone: "0521234567",
    email: "ronit@gan-shemesh.co.il",
    urgent: false,
    status: "completed",
    customerType: "existing",
    courseType: "עזרה ראשונה 44 שעות",
    courseHours: 44,
    category: "גני ילדים",
    pricingType: "global",
    pricePerUnit: 0,
    participantsCount: 8,
    totalPrice: 6800,
    certificateDelivery: "mail",
    address: { street: "רחוב הפרחים", houseNumber: "8", city: "תל אביב", zip: "6100000" },
    date: daysFromNow(-20),
    time: "08:30",
    instructor: "מירב שרון",
    contactName: "רונית ברק",
    kindergartenApproval: true,
    trainingIndex: 2,
    participants: [
      { id: "p4", name: "אורנה מור", idNumber: "311111111" },
      { id: "p5", name: "גלית פז", idNumber: "322222222" },
    ],
    expenses: [
      { id: "e3", type: "נסיעות", amount: 200, hasReceipt: true, date: daysFromNow(-20) },
      { id: "e4", type: "הדפסת תעודות", amount: 90, hasReceipt: false, date: daysFromNow(-18) },
    ],
    createdAt: daysFromNow(-50),
    updatedAt: daysFromNow(-18),
  },
  {
    id: "l5",
    clientId: "c1",
    name: "גן שמש",
    phone: "0521234567",
    urgent: false,
    status: "done",
    customerType: "existing",
    courseType: "בטיחות בגובה",
    courseHours: 12,
    category: "גני ילדים",
    pricingType: "per_participant",
    pricePerUnit: 220,
    participantsCount: 6,
    totalPrice: 1320,
    certificateDelivery: "digital",
    address: { street: "רחוב הפרחים", houseNumber: "8", city: "תל אביב" },
    date: daysFromNow(-1),
    time: "10:00",
    instructor: "יוסי מזרחי",
    contactName: "רונית ברק",
    trainingIndex: 3,
    participants: [{ id: "p6", name: "נועה שלו", idNumber: "333333333" }],
    expenses: [],
    createdAt: daysFromNow(-12),
    updatedAt: daysFromNow(-1),
  },
]

export const DEMO_EQUIPMENT: EquipmentDeal[] = [
  {
    id: "eq1",
    clientId: "c2",
    title: "ערכות עזרה ראשונה x20",
    status: "invoice",
    amount: 8400,
    paymentTerms: "net30",
    contactName: "משה פרץ",
    phone: "0539876543",
    notes: "אספקה למחסן המרכזי",
    createdAt: daysFromNow(-14),
    updatedAt: daysFromNow(-2),
  },
  {
    id: "eq2",
    clientId: "c1",
    title: "מטפי כיבוי אש x6",
    status: "quote",
    amount: 1800,
    paymentTerms: "immediate",
    contactName: "רונית ברק",
    phone: "0521234567",
    createdAt: daysFromNow(-5),
    updatedAt: daysFromNow(-4),
  },
  {
    id: "eq3",
    clientId: "c3",
    title: "דפיברילטור AED",
    status: "paid",
    amount: 5500,
    paymentTerms: "immediate",
    contactName: "טלי אבנר",
    phone: "0547778899",
    createdAt: daysFromNow(-25),
    updatedAt: daysFromNow(-20),
  },
]

export const DEMO_TASKS: Task[] = [
  {
    id: "t1",
    title: "להתקשר שוב - מסעדת הים",
    date: daysFromNow(0),
    time: "12:00",
    assignee: "אני",
    note: "לסגור תאריך להדרכת החייאה",
    done: false,
    relatedLeadId: "l1",
    type: "callback",
  },
  {
    id: "t2",
    title: "גבייה - מפעלי הגליל (שוטף+30)",
    date: daysFromNow(16),
    assignee: "מזכירה",
    note: "חשבונית eq1 - שוטף+30",
    done: false,
    type: "collection",
  },
  {
    id: "t3",
    title: "הדרכה - עזרה ראשונה - באר שבע",
    date: daysFromNow(5),
    time: "09:00",
    assignee: "דנה כהן",
    done: false,
    relatedLeadId: "l2",
    type: "general",
  },
  {
    id: "t4",
    title: "לשלוח תעודות - מפעלי הגליל",
    date: daysFromNow(1),
    assignee: "אני",
    done: false,
    relatedLeadId: "l3",
    type: "general",
  },
]
